// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBfVfFteIQq2D7lAYNtTXtzk0yQMbUk4bU',
    appId: '1:96810848682:web:87d9e1238966ae0d29dbd3',
    messagingSenderId: '96810848682',
    projectId: 'stepwise-b8cf2',
    authDomain: 'stepwise-b8cf2.firebaseapp.com',
    storageBucket: 'stepwise-b8cf2.firebasestorage.app',
    measurementId: 'G-YRLDYLB61D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCvwIH-85yrd3AjS47Cg-wstK7yOYSnu0w',
    appId: '1:96810848682:android:eb953c766ddc8d0029dbd3',
    messagingSenderId: '96810848682',
    projectId: 'stepwise-b8cf2',
    storageBucket: 'stepwise-b8cf2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA6LxMzOPElN_sQjyAhc2fCKqwqSW1jmhc',
    appId: '1:96810848682:ios:1cafd8e34fd9071c29dbd3',
    messagingSenderId: '96810848682',
    projectId: 'stepwise-b8cf2',
    storageBucket: 'stepwise-b8cf2.firebasestorage.app',
    iosBundleId: 'com.example.stepwise',
  );
}
